apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: '2019-08-12T14:14:01Z'
  generation: 1
  name: got-seasons
  namespace: tekton-pipelines
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  serviceAccount: pipeline
  tasks:
    - name: got-season-8-episodes
      taskRef:
        name: got-season-8-episodes
    - name: got-season-7-2
      taskRef:
        name: got-season-7-2
    - name: got-season-1-episodes
      taskRef:
        name: got-season-1-episodes
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: got-season-8-episodes
spec:
  steps:
  - name: wait
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: season-1
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'cannot fetch the list...'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: got-season-7-2
spec:
  steps:
  - name: wait
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: season-1
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'cannot fetch the list...'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: got-season-1-episodes
spec:
  steps:
  - name: fetching-ep-1
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Fetching Episode 1'
  - name: wait-ep-1
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: ep-1
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Successfully fetched Episode 1 - Winter is Coming'
  - name: fetching-ep-2
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Fetching Episode 2'
  - name: wait-ep-2
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: ep-2
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Successfully fetched Episode 2 - The Night Lands'
  - name: fetching-ep-3
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Fetching Episode 3'
  - name: wait-ep-3
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: ep-3
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Successfully fetched Episode 3 - What Is Dead May Never Die'
  - name: fetching-ep-4
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Fetching Episode 4'
  - name: wait-ep-4
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: ep-4
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Successfully fetched Episode 4 - Garden of Bones'
  - name: fetching-ep-5
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Fetching Episode 5'
  - name: wait-ep-5
    image: busybox
    command:
    - sleep
    args:
    - "1"
  - name: ep-5
    image: busybox
    command:
    - /bin/sh
    args:
    - '-c'
    - echo 'Successfully fetched Episode 5 - The Ghost of Harrenhal'
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: got-seasons
  name: got-seasons-0rcdw5
  namespace: tekton-pipelines
spec:
  params: null
  pipelineRef:
    name: got-seasons
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  serviceAccount: pipeline
  trigger:
    type: manual
---